#!/bin/sh

####################################################################################################
# Environment variables

# must install theme before using it
export GTK_THEME=Dracula

# export monitor names as env variable
export PRIMARY_MONITOR="$(xrandr -q | grep " connected primary" | cut -d ' ' -f1)"
export SECONDARY_MONITOR="$(xrandr -q | grep " connected 1" | cut -d ' ' -f1)"
