preload = ~/Pictures/Wallpapers/home.png

# set the default wallpaper(s) seen on initial workspace(s)
wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/home.png
    fit_mode = cover
}

# if more than one monitor in use, load the same or a 2nd image
wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpapers/home.png
    fit_mode = cover
}

# enable splash text rendering over the wallpaper
splash = true

# fully disable ipc
ipc = off
